name: Build RVA:TAC
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.15f1
          targetPlatform: Android
          buildName: RVATAC
          
      - uses: game-ci/unity-test-runner@v2
        with:
          testMode: all
          
      - uses: actions/upload-artifact@v3
        with:
          name: RVA-TAC-Android
          path: build/Android/RVATAC.apk
